// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project02.Models;

namespace Project02.Migrations
{
    [DbContext(typeof(TempleToursContext))]
    [Migration("20220324033806_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Project02.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentID");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentID = 1,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 2,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 3,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 4,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 5,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 6,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 7,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 8,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 9,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 10,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 11,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 12,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 13,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 23, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 14,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 15,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 16,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 17,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 18,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 19,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 20,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 21,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 22,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 23,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 24,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 25,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 26,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 24, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 27,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 28,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 29,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 30,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 31,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 32,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 33,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 34,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 35,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 36,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 37,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 38,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 39,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 25, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 40,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 41,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 42,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 43,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 44,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 45,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 46,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 47,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 48,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 49,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 50,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 51,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 52,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 26, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 53,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 54,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 55,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 56,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 57,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 58,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 59,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 60,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 61,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 62,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 63,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 64,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 65,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 27, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 66,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 67,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 68,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 69,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 70,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 71,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 72,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 73,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 74,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 75,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 76,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 77,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 78,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 28, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 79,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 80,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 81,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 82,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 83,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 84,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 85,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 86,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 87,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 88,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 89,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 90,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 91,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 29, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 92,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 93,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 94,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 95,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 96,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 97,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 98,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 99,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 100,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 101,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 102,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 103,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 104,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 30, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 105,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 106,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 107,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 108,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 109,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 110,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 111,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 112,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 113,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 114,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 115,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 116,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 117,
                            GroupSize = 0,
                            Start = new DateTime(2022, 3, 31, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 118,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 119,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 120,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 121,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 122,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 123,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 124,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 125,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 126,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 127,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 128,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 129,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentID = 130,
                            GroupSize = 0,
                            Start = new DateTime(2022, 4, 1, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
