// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project02.Models;

namespace Project02.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20220324155010_MoreContext")]
    partial class MoreContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Project02.Models.Appointment", b =>
                {
                    b.Property<long>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "8"
                        },
                        new
                        {
                            AppointmentId = 2L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "9"
                        },
                        new
                        {
                            AppointmentId = 3L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "10"
                        },
                        new
                        {
                            AppointmentId = 4L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "11"
                        },
                        new
                        {
                            AppointmentId = 5L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "12"
                        },
                        new
                        {
                            AppointmentId = 6L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "13"
                        },
                        new
                        {
                            AppointmentId = 7L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "14"
                        },
                        new
                        {
                            AppointmentId = 8L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "15"
                        },
                        new
                        {
                            AppointmentId = 9L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "16"
                        },
                        new
                        {
                            AppointmentId = 10L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "17"
                        },
                        new
                        {
                            AppointmentId = 11L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "18"
                        },
                        new
                        {
                            AppointmentId = 12L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "19"
                        },
                        new
                        {
                            AppointmentId = 13L,
                            Available = true,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            Time = "20"
                        },
                        new
                        {
                            AppointmentId = 14L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "8"
                        },
                        new
                        {
                            AppointmentId = 15L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "9"
                        },
                        new
                        {
                            AppointmentId = 16L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "10"
                        },
                        new
                        {
                            AppointmentId = 17L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "11"
                        },
                        new
                        {
                            AppointmentId = 18L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "12"
                        },
                        new
                        {
                            AppointmentId = 19L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "13"
                        },
                        new
                        {
                            AppointmentId = 20L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "14"
                        },
                        new
                        {
                            AppointmentId = 21L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "15"
                        },
                        new
                        {
                            AppointmentId = 22L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "16"
                        },
                        new
                        {
                            AppointmentId = 23L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "17"
                        },
                        new
                        {
                            AppointmentId = 24L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "18"
                        },
                        new
                        {
                            AppointmentId = 25L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "19"
                        },
                        new
                        {
                            AppointmentId = 26L,
                            Available = true,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            Time = "20"
                        },
                        new
                        {
                            AppointmentId = 27L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "8"
                        },
                        new
                        {
                            AppointmentId = 28L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "9"
                        },
                        new
                        {
                            AppointmentId = 29L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "10"
                        },
                        new
                        {
                            AppointmentId = 30L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "11"
                        },
                        new
                        {
                            AppointmentId = 31L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "12"
                        },
                        new
                        {
                            AppointmentId = 32L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "13"
                        },
                        new
                        {
                            AppointmentId = 33L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "14"
                        },
                        new
                        {
                            AppointmentId = 34L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "15"
                        },
                        new
                        {
                            AppointmentId = 35L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "16"
                        },
                        new
                        {
                            AppointmentId = 36L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "17"
                        },
                        new
                        {
                            AppointmentId = 37L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "18"
                        },
                        new
                        {
                            AppointmentId = 38L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "19"
                        },
                        new
                        {
                            AppointmentId = 39L,
                            Available = true,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            Time = "20"
                        },
                        new
                        {
                            AppointmentId = 40L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "8"
                        },
                        new
                        {
                            AppointmentId = 41L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "9"
                        },
                        new
                        {
                            AppointmentId = 42L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "10"
                        },
                        new
                        {
                            AppointmentId = 43L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "11"
                        },
                        new
                        {
                            AppointmentId = 44L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "12"
                        },
                        new
                        {
                            AppointmentId = 45L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "13"
                        },
                        new
                        {
                            AppointmentId = 46L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "14"
                        },
                        new
                        {
                            AppointmentId = 47L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "15"
                        },
                        new
                        {
                            AppointmentId = 48L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "16"
                        },
                        new
                        {
                            AppointmentId = 49L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "17"
                        },
                        new
                        {
                            AppointmentId = 50L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "18"
                        },
                        new
                        {
                            AppointmentId = 51L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "19"
                        },
                        new
                        {
                            AppointmentId = 52L,
                            Available = true,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            Time = "20"
                        },
                        new
                        {
                            AppointmentId = 53L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "8"
                        },
                        new
                        {
                            AppointmentId = 54L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "9"
                        },
                        new
                        {
                            AppointmentId = 55L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "10"
                        },
                        new
                        {
                            AppointmentId = 56L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "11"
                        },
                        new
                        {
                            AppointmentId = 57L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "12"
                        },
                        new
                        {
                            AppointmentId = 58L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "13"
                        },
                        new
                        {
                            AppointmentId = 59L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "14"
                        },
                        new
                        {
                            AppointmentId = 60L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "15"
                        },
                        new
                        {
                            AppointmentId = 61L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "16"
                        },
                        new
                        {
                            AppointmentId = 62L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "17"
                        },
                        new
                        {
                            AppointmentId = 63L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "18"
                        },
                        new
                        {
                            AppointmentId = 64L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "19"
                        },
                        new
                        {
                            AppointmentId = 65L,
                            Available = true,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            Time = "20"
                        },
                        new
                        {
                            AppointmentId = 66L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "8"
                        },
                        new
                        {
                            AppointmentId = 67L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "9"
                        },
                        new
                        {
                            AppointmentId = 68L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "10"
                        },
                        new
                        {
                            AppointmentId = 69L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "11"
                        },
                        new
                        {
                            AppointmentId = 70L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "12"
                        },
                        new
                        {
                            AppointmentId = 71L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "13"
                        },
                        new
                        {
                            AppointmentId = 72L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "14"
                        },
                        new
                        {
                            AppointmentId = 73L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "15"
                        },
                        new
                        {
                            AppointmentId = 74L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "16"
                        },
                        new
                        {
                            AppointmentId = 75L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "17"
                        },
                        new
                        {
                            AppointmentId = 76L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "18"
                        },
                        new
                        {
                            AppointmentId = 77L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "19"
                        },
                        new
                        {
                            AppointmentId = 78L,
                            Available = true,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            Time = "20"
                        },
                        new
                        {
                            AppointmentId = 79L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "8"
                        },
                        new
                        {
                            AppointmentId = 80L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "9"
                        },
                        new
                        {
                            AppointmentId = 81L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "10"
                        },
                        new
                        {
                            AppointmentId = 82L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "11"
                        },
                        new
                        {
                            AppointmentId = 83L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "12"
                        },
                        new
                        {
                            AppointmentId = 84L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "13"
                        },
                        new
                        {
                            AppointmentId = 85L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "14"
                        },
                        new
                        {
                            AppointmentId = 86L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "15"
                        },
                        new
                        {
                            AppointmentId = 87L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "16"
                        },
                        new
                        {
                            AppointmentId = 88L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "17"
                        },
                        new
                        {
                            AppointmentId = 89L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "18"
                        },
                        new
                        {
                            AppointmentId = 90L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "19"
                        },
                        new
                        {
                            AppointmentId = 91L,
                            Available = true,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            Time = "20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
